In [1]:
import sys
import os

sys.path.append(os.path.abspath("../../"))

from src.data.load_data import load_data
from src.data.preprocess import clean_data

df = load_data("../../data/raw/Housing.csv")
df = clean_data(df)

✅ Data loaded successfully

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    float64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    int64
 6   guestroom         545 non-null    int64
 7   basement          545 non-null    int64
 8   hotwaterheating   545 non-null    int64
 9   airconditioning   545 non-null    int64
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    int64
 12  furnishingstatus  545 non-null    object
dtypes: float64(1), int64(11), object(1)
memory usage: 55.5+ KB

In [3]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,5146.369485,4,2,3,1,0,0,0,1,2,1,furnished
1,12250000,8960.000000,4,4,4,1,0,0,0,1,3,0,semi-furnished
2,12250000,9960.000000,3,2,2,1,0,1,0,0,2,1,semi-furnished
3,12215000,7500.000000,4,2,2,1,0,1,0,1,3,1,furnished
4,11410000,7420.000000,4,1,2,1,1,1,0,1,2,0,furnished

In [4]:
df.shape

(545, 13)

In [5]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [6]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [7]:
df.isnull().any()  # True/False if any missing

price               False
area                False
bedrooms            False
bathrooms           False
stories             False
mainroad            False
guestroom           False
basement            False
hotwaterheating     False
airconditioning     False
parking             False
prefarea            False
furnishingstatus    False
dtype: bool

In [8]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

print("Numeric:", num_cols)
print("Categorical:", cat_cols)

Numeric: Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea'],
      dtype='object')
Categorical: Index(['furnishingstatus'], dtype='object')

In [9]:
for col in num_cols:
    df[col] = df[col].fillna(df[col].mean())

In [10]:
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [11]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [12]:
df_3bed = df[df['bedrooms'] > 3]
df_3bed.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,5146.369485,4,2,3,1,0,0,0,1,2,1,furnished
1,12250000,8960.000000,4,4,4,1,0,0,0,1,3,0,semi-furnished
3,12215000,7500.000000,4,2,2,1,0,1,0,1,3,1,furnished
4,11410000,7420.000000,4,1,2,1,1,1,0,1,2,0,furnished
6,10150000,8580.000000,4,3,4,1,0,0,0,1,2,1,semi-furnished

In [13]:
q1 = df['price'].quantile(0.01)
q99 = df['price'].quantile(0.99)

df = df[(df['price'] > q1) & (df['price'] < q99)]

In [14]:
df.to_csv("../../data/processed/cleaned_housing.csv", index=False)